[Unit]
Description=Telegram bot @AshleyBot
Requires=redis.service

[Service]
User=ashley
Group=ashley
WorkingDirectory=/home/ashley/ashlee
ExecStart=/home/ashley/ashlee/venv/bin/python -m ashlee
Restart=always
KillMode=process
TimeoutSec=300
RestartSec=30
StartLimitIntervalSec=300
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
