name: tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
          architecture: x64
      - name: Checkout
        uses: actions/checkout@main
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 ashlee --max-line-length=127 --show-source --statistics --exclude .git,__pycache__,venv